add gitconfig

diff --git a/scripts/ghpr b/scripts/ghpr
--- a/scripts/ghpr
+++ b/scripts/ghpr
@@ -32,10 +32,33 @@ if [ "$LOCAL" != "$REMOTE" ]; then
 fi
 
 TEMP_FILE=$(mktemp)
+TEMPLATE_CONTENTS="
+
+## Purpose of PR
+
+## Parts of the app this will impact
+
+## Todos
+
+## Additional information
+
+## Related links
+https://edited.atlassian.net/browse/
+
+"
+
+echo "$TEMPLATE_CONTENTS" > "$TEMP_FILE"
+
 $EDITOR "$TEMP_FILE"
 
 TITLE=$(head -n 1 "$TEMP_FILE")
 BODY=$(tail -n +2 "$TEMP_FILE")
+
+if cmp -s <(echo "$TEMPLATE_CONTENTS") "$TEMP_FILE"; then
+    echo "Error: Nothing added; aborting PR creation."
+    rm "$TEMP_FILE"
+    exit 1
+fi
 
 if [ -z "$TITLE" ]; then
     echo "Error: PR title cannot be empty."
